<?php
return array(
    array(
        "text"=>"首页",
        "active"=>"homePage",
        "url"=>"homePage/index",
    ),
    array(
        "text"=>"我的订单",
        "active"=>"order",
    	"child"=>array(
            array(
                "text"=>"创建新订单",
                "active"=>"add",
                "url"=>"order/agreement",
            ),
            array(
                "text"=>"订单列表",
                "active"=>"index",
                "url"=>"order/index",
            ),
        ),
    ),
    array(
        "text"=>"我的资料",
        "active"=>"user",
        "child"=>array(
            array(
                "text"=>"查看资料",
                "active"=>"info",
                "url"=>"user/info",
            ),
            array(
                "text"=>"修改密码",
                "active"=>"changePwd",
                "url"=>"user/changePwd",
            ),
            array(
                "text"=>"我的积分",
                "active"=>"score",
                "url"=>"user/score",
            ),
        ),
    ),
    array(
        "text"=>"请您建议",
        "active"=>"contact",
        "url"=>"user/contact",
    ),
);